Anthony Baryshnikov HashMap
abarankab/simple_hashtable pull request #1
Opened 2020-02-17 20:06 UTC by abarankab

2020-03-11 09:38 UTC, sartuhin commented on main.h
> +        for (size_t i = 0; i < table[bucket].size(); ++i) {
Лучше использовать более говорящие названием переменных чем i для циклов больше 1 строчки.

2020-03-11 09:38 UTC, sartuhin commented on main.h
> +    HashMap(It begin,
Изменять внутри функции входные параметры которые этого не подразумевают не стоит.

2020-03-11 09:40 UTC, sartuhin commented on main.h
> +    std::list<std::pair<const KeyType, ValueType>> data;
std::pair<const KeyType, ValueType> лучше вынести в отдельный тип.

2020-03-11 09:40 UTC, sartuhin requested changes
.

2020-04-30 07:51 UTC, sartuhin requested changes

2020-04-30 07:51 UTC, sartuhin commented on main.h
> +    HashMap(It begin,
Почему end - const а begin нет?

2020-04-30 07:54 UTC, abarankab commented on main.h
> +    HashMap(It begin,
Поправил в новом коммите

2020-04-30 08:38 UTC, sartuhin approved these changes

2020-04-30 08:38 UTC, merged